spring:
  # 1. DB 접속 설정
  datasource:
    url: jdbc:mysql://seoul-study-db.cpckamguw5kr.ap-northeast-2.rds.amazonaws.com:3306/team_project_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: whiteStudy
    password: JhgdLkhzgjUtKhDwTIqB
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # 3. 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 4. 서버 포트
server:
  port: 8081

# 5. AWS S3 설정
cloud:
  aws:
    s3:
      bucket: team-project-images-2025
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false